sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6.5
install:
  - pip install tox tox-travis
  - pip install coverage coveralls
  - pip install ccxt
script:
  - python --version
  - python -m unittest discover test
